In [18]:
import pandas as pd

df=pd.read_csv('students.csv', index_col=0)
df

      國文   英文  數學   自然   社會
余宗儒   73   82  62   54   86
劉佳佩   95   70  56   78   52
沈心利   75   58  55   59   96
游詩亞   55   56  63   96   95
彭茹靖   65   50  62   78   57
張軒宸  100   85  96   82   71
朱惠儀   94   56  63   61   61
鄭孟芳   94   68  76   69   76
黃佩芬  100   60  91   73   64
楊易政   94   82  71   68   70
潘英迪   54   77  87   56   90
劉慧君   98   94  99   75   65
陳信念   98   87  98   58   55
謝佳穎   66   91  71   58   71
楊韻如   54   90  86   57   97
程玫靖   73   83  90  100   60
黃彥孝   80   86  63   66   85
王志謙   64   78  51   90   77
陳倩潔   89   86  51   90   84
吳俐芷   87   56  61   74   61
黃健發   96   61  91   89   61
方雅慧   54   78  75   99   73
蘇凡菁   50   99  56   92   97
王士銘   71   66  50   60   58
陳逸凡   99   92  95   51   89
白世宏   54   98  64   51   61
余月修   59   72  82   81   76
胡淑貞   79   90  85   94   84
陳怡容   70   79  88   72  100
李慈啟   89   69  90   54   75
林淑安   84   68  57   68   97
蔡世馨   67   72  98   54   58
鄭佳玲   78   66  61   63   69
陳怡伶   76   87  82   68   90
金宜芳   51   87  94   92   51
游倫城   55   97  53   54   93
吳麗卿   71  100  87  100   85
李慶亮   57   74  63   89   80
王柏聖   54   75  77   56   59
賴心怡   66   66  90   77   79
盧必妍   99   59  72   55   97
吳志宣   94   80  72   75   53
鄧亭聿   89   87  57  100   80
白美珍   80   63  76   98   98
王人仰   91   56  51   90   81
陳得映   67   51  78   72   61
張婕妤   55   75  94   97   92
周家銘   98   51  59   67   79
李湘婷   94   56  79   88   64
唐雪豪   59   66  70   51   92

In [19]:
df=pd.read_excel('students.xlsx', index_col=0)
df.head()  #預設是5，改成顯示5筆資料

     國文  英文  數學  自然  社會
余宗儒  73  82  62  54  86
劉佳佩  95  70  56  78  52
沈心利  75  58  55  59  96
游詩亞  55  56  63  96  95
彭茹靖  65  50  62  78  57

### **-透過欄選取**
### **-透過列選取**

In [20]:
# 透過欄選取
# 單欄選取
df['國文']  #class_series

余宗儒     73
劉佳佩     95
沈心利     75
游詩亞     55
彭茹靖     65
張軒宸    100
朱惠儀     94
鄭孟芳     94
黃佩芬    100
楊易政     94
潘英迪     54
劉慧君     98
陳信念     98
謝佳穎     66
楊韻如     54
程玫靖     73
黃彥孝     80
王志謙     64
陳倩潔     89
吳俐芷     87
黃健發     96
方雅慧     54
蘇凡菁     50
王士銘     71
陳逸凡     99
白世宏     54
余月修     59
胡淑貞     79
陳怡容     70
李慈啟     89
林淑安     84
蔡世馨     67
鄭佳玲     78
陳怡伶     76
金宜芳     51
游倫城     55
吳麗卿     71
李慶亮     57
王柏聖     54
賴心怡     66
盧必妍     99
吳志宣     94
鄧亭聿     89
白美珍     80
王人仰     91
陳得映     67
張婕妤     55
周家銘     98
李湘婷     94
唐雪豪     59
Name: 國文, dtype: int64

In [21]:
# 多欄選取
df[['國文','英文']]  #class_dataframe (裡面有兩個series)

      國文   英文
余宗儒   73   82
劉佳佩   95   70
沈心利   75   58
游詩亞   55   56
彭茹靖   65   50
張軒宸  100   85
朱惠儀   94   56
鄭孟芳   94   68
黃佩芬  100   60
楊易政   94   82
潘英迪   54   77
劉慧君   98   94
陳信念   98   87
謝佳穎   66   91
楊韻如   54   90
程玫靖   73   83
黃彥孝   80   86
王志謙   64   78
陳倩潔   89   86
吳俐芷   87   56
黃健發   96   61
方雅慧   54   78
蘇凡菁   50   99
王士銘   71   66
陳逸凡   99   92
白世宏   54   98
余月修   59   72
胡淑貞   79   90
陳怡容   70   79
李慈啟   89   69
林淑安   84   68
蔡世馨   67   72
鄭佳玲   78   66
陳怡伶   76   87
金宜芳   51   87
游倫城   55   97
吳麗卿   71  100
李慶亮   57   74
王柏聖   54   75
賴心怡   66   66
盧必妍   99   59
吳志宣   94   80
鄧亭聿   89   87
白美珍   80   63
王人仰   91   56
陳得映   67   51
張婕妤   55   75
周家銘   98   51
李湘婷   94   56
唐雪豪   59   66

In [32]:
# 透過列選取
# loc->使用索引的名稱
# iloc->使用索引的index

print(df.loc['余宗儒'])
df.loc[['余宗儒','游詩亞']]

國文    73
英文    82
數學    62
自然    54
社會    86
Name: 余宗儒, dtype: int64

     國文  英文  數學  自然  社會
余宗儒  73  82  62  54  86
游詩亞  55  56  63  96  95

In [31]:
print(df.iloc[0])
df.iloc[[0,3]]

國文    73
英文    82
數學    62
自然    54
社會    86
Name: 余宗儒, dtype: int64

     國文  英文  數學  自然  社會
余宗儒  73  82  62  54  86
游詩亞  55  56  63  96  95

In [29]:
df.loc['余宗儒':'游詩亞']

     國文  英文  數學  自然  社會
余宗儒  73  82  62  54  86
劉佳佩  95  70  56  78  52
沈心利  75  58  55  59  96
游詩亞  55  56  63  96  95

In [30]:
df.iloc[0:3]

     國文  英文  數學  自然  社會
余宗儒  73  82  62  54  86
劉佳佩  95  70  56  78  52
沈心利  75  58  55  59  96

In [34]:
df.head()
df.loc['彭茹靖','英文']=61  #修改資料
df.head()

     國文  英文  數學  自然  社會
余宗儒  73  82  62  54  86
劉佳佩  95  70  56  78  52
沈心利  75  58  55  59  96
游詩亞  55  56  63  96  95
彭茹靖  65  61  62  78  57

In [38]:
df[:10]     #取前10列資料，如果是用欄標題SLICE會失敗

      國文  英文  數學  自然  社會
余宗儒   73  82  62  54  86
劉佳佩   95  70  56  78  52
沈心利   75  58  55  59  96
游詩亞   55  56  63  96  95
彭茹靖   65  61  62  78  57
張軒宸  100  85  96  82  71
朱惠儀   94  56  63  61  61
鄭孟芳   94  68  76  69  76
黃佩芬  100  60  91  73  64
楊易政   94  82  71  68  70

In [39]:
df[-10:]    #取後10列資料

     國文  英文  數學   自然  社會
盧必妍  99  59  72   55  97
吳志宣  94  80  72   75  53
鄧亭聿  89  87  57  100  80
白美珍  80  63  76   98  98
王人仰  91  56  51   90  81
陳得映  67  51  78   72  61
張婕妤  55  75  94   97  92
周家銘  98  51  59   67  79
李湘婷  94  56  79   88  64
唐雪豪  59  66  70   51  92

In [ ]:
df['國文'] + df['英文'] + df['數學'] + df['自然'] + df['社會']  #series可以做陣列運算

余宗儒    357
劉佳佩    351
沈心利    343
游詩亞    365
彭茹靖    323
張軒宸    434
朱惠儀    335
鄭孟芳    383
黃佩芬    388
楊易政    385
潘英迪    364
劉慧君    431
陳信念    396
謝佳穎    357
楊韻如    384
程玫靖    406
黃彥孝    380
王志謙    360
陳倩潔    400
吳俐芷    339
黃健發    398
方雅慧    379
蘇凡菁    394
王士銘    305
陳逸凡    426
白世宏    328
余月修    370
胡淑貞    432
陳怡容    409
李慈啟    377
林淑安    374
蔡世馨    349
鄭佳玲    337
陳怡伶    403
金宜芳    375
游倫城    352
吳麗卿    443
李慶亮    363
王柏聖    321
賴心怡    378
盧必妍    382
吳志宣    374
鄧亭聿    413
白美珍    415
王人仰    369
陳得映    329
張婕妤    413
周家銘    354
李湘婷    381
唐雪豪    338
dtype: int64

In [45]:
stu_sum = df.sum(axis=1) #axis=1是指橫向加總
stu_mean = df.sum(axis=1) / 5

In [46]:
df['總分'] = stu_sum
df['平均'] = stu_mean

In [47]:
df

      國文   英文  數學   自然   社會   總分    平均
余宗儒   73   82  62   54   86  357  71.4
劉佳佩   95   70  56   78   52  351  70.2
沈心利   75   58  55   59   96  343  68.6
游詩亞   55   56  63   96   95  365  73.0
彭茹靖   65   61  62   78   57  323  64.6
張軒宸  100   85  96   82   71  434  86.8
朱惠儀   94   56  63   61   61  335  67.0
鄭孟芳   94   68  76   69   76  383  76.6
黃佩芬  100   60  91   73   64  388  77.6
楊易政   94   82  71   68   70  385  77.0
潘英迪   54   77  87   56   90  364  72.8
劉慧君   98   94  99   75   65  431  86.2
陳信念   98   87  98   58   55  396  79.2
謝佳穎   66   91  71   58   71  357  71.4
楊韻如   54   90  86   57   97  384  76.8
程玫靖   73   83  90  100   60  406  81.2
黃彥孝   80   86  63   66   85  380  76.0
王志謙   64   78  51   90   77  360  72.0
陳倩潔   89   86  51   90   84  400  80.0
吳俐芷   87   56  61   74   61  339  67.8
黃健發   96   61  91   89   61  398  79.6
方雅慧   54   78  75   99   73  379  75.8
蘇凡菁   50   99  56   92   97  394  78.8
王士銘   71   66  50   60   58  305  61.0
陳逸凡   99   92  95   51   89  426  85.2
白世宏   54   98  64   51   61  328  65.6
余月修   59   72  82   81   76  370  74.0
胡淑貞   79   90  85   94   84  432  86.4
陳怡容   70   79  88   72  100  409  81.8
李慈啟   89   69  90   54   75  377  75.4
林淑安   84   68  57   68   97  374  74.8
蔡世馨   67   72  98   54   58  349  69.8
鄭佳玲   78   66  61   63   69  337  67.4
陳怡伶   76   87  82   68   90  403  80.6
金宜芳   51   87  94   92   51  375  75.0
游倫城   55   97  53   54   93  352  70.4
吳麗卿   71  100  87  100   85  443  88.6
李慶亮   57   74  63   89   80  363  72.6
王柏聖   54   75  77   56   59  321  64.2
賴心怡   66   66  90   77   79  378  75.6
盧必妍   99   59  72   55   97  382  76.4
吳志宣   94   80  72   75   53  374  74.8
鄧亭聿   89   87  57  100   80  413  82.6
白美珍   80   63  76   98   98  415  83.0
王人仰   91   56  51   90   81  369  73.8
陳得映   67   51  78   72   61  329  65.8
張婕妤   55   75  94   97   92  413  82.6
周家銘   98   51  59   67   79  354  70.8
李湘婷   94   56  79   88   64  381  76.2
唐雪豪   59   66  70   51   92  338  67.6